import React from "react";
import ImageCarousel from "@/components/ImageCarousel";
import HoverPreview from "@/components/HoverPreview";
import MiniGraph from "@/components/MiniGraph";
import FigureImage from "@/components/FigureImage";

export default function Content() {
  return (
    <article className="space-y-8">
      <section>
      <FigureImage
        lightSrc="/write-up/ppi-overview-light.png"
        darkSrc="/write-up/images/dark/intro-dark.png"
        alt="Overview of the PPI graph"
      />
      <p>We have a lot of biology data out there. While not enough to train AIs to solve all of biology, a large amount of insight is waiting to be discovered in the data we already have. But often, our tools show us exactly what we are looking for, limiting our ability to discover unknown unknowns through open-ended data exploration.  </p>
      <p>This was the feeling we had reading the <a href="https://www.science.org/doi/10.1126/science.adt1630">recent paper</a> from Baker’s Lab on their protein-protein interaction (PPI) dataset. The dataset contains predictions for over 200m potential PPIs, generated using RF2-PPI with confidence scores fromAlphaFold 2, earning the prediction pipeline the shortened name RF2/AF2. The research paper reported that, at 90% precision level, the model predicted 17,849 PPIs, including 3,631 new PPIs that have not been previously identified in previous experimental screens. We couldn’t help the impression that there were some important breakthroughs and novelties here, elusively hidden behind the walls of texts and dataframes. How can we explore this huge dataset, if what we are looking for is an unknown unknown?</p>  
      <p>Fortunately, PPIs are a relatively simple type of data: it’s a graph! Each entry includes two columns: protein 1 and protein 2, indicating these two proteins interact. So during the Hackathon at LBF7 in Valencia, our team (Alex, Cat, Faizan and Tom) performed an evaluation of the predictions and built a tool to visualize this dataset.</p>
      </section>

      <section>
        <h2>But first, what do we already know about protein-protein interactions?</h2>

        <p>Proteins perform their function by forming physical contacts with other proteins. Sometimes this contact is fleeting during signaling; other times they form stable complexes that carry out cellular functions. These PPIs define how pathways and structures come together.</p>
        <p>Most of what we know about PPIs comes from experimental screens. Over the years, thousands of such studies have been aggregated into large curated databases like <a href="https://thebiogrid.org/">BioGRID</a> or <a href="https://string-db.org/">STRING</a>, where curators annotate each interaction and evaluate the strength of evidence. These experimental databases have become valuable references for biological research.</p>
        <p>Still, they are far from perfect. These screens create lab controlled environments so we can detect if two proteins bind to each other; as a result, these methods suffer from a large false positive and negative rate, as an effect of those artificial environments. False positives, for example, can be caused by proteins binding to experimental artifacts, while false negatives by interactions that are too fleeting or condition-specific. </p>
        <p>In total current databases contain 1m PPIs, of which 900k are believed to be false positives.</p>
        <p>RF2/AF2 expands the scope of evidence beyond empirical observations. The training started with experimental data from the Protein Data Bank, which was then augmented with a few clever ideas, including a secondary dataset generated from the AlphaFold Protein Structure Database – a database containing predicted protein structures by AlphaFold. High-confidence predictions by RF2-PPI had their 3D structures generated by AlphaFold 2 to verify that they plausibly interact.</p>
        <p>From this came a large number of new, high-confidence interactions:  perhaps this could unveil unknown unknowns about cell biology!</p>
      </section>

      <section>
        <h2>The Visualization</h2>

        <p>Each protein in the dataset is represented as a node in the graph. The size and centrality of a node are determined by the number of interactions the protein has.</p>
        <div className="legend-2col my-8">
          <div className="flex flex-col items-center">
            <svg width="40" height="40">
              <circle cx="20" cy="20" r="12" fill="#bbb" />
            </svg>
            <span className="text-xs mt-2 text-gray-500">protein with few interactions</span>
          </div>
          <div className="flex flex-col items-center">
            <svg width="80" height="80">
              <circle cx="40" cy="40" r="28" fill="#bbb" />
            </svg>
            <span className="text-xs mt-2 text-gray-500">protein with many interactions</span>
          </div>
        </div>

        <p>Node coloring conveys information about novelty.</p>
        <div className="legend-2col my-8">
          <div className="flex flex-col items-center">
            <svg width="56" height="56">
              <circle cx="28" cy="28" r="16" fill="#bbb" />
            </svg>
            <span className="text-xs mt-2 text-gray-500">no new interactions (all exist major databases)</span>
          </div>
          <div className="flex flex-col items-center">
            <svg width="56" height="56">
              <circle cx="28" cy="28" r="16" fill="#93c5fd" />
            </svg>
            <span className="text-xs mt-2 text-gray-500">has ≥1 new interaction</span>
          </div>
        </div>
        <p>The darker the blue, the higher the number of new interactions.</p>
        <div className="legend-2col my-6">
          <div className="flex flex-col items-center">
            <svg width="56" height="56">
              <circle cx="28" cy="28" r="16" fill="#93c5fd" />
            </svg>
            <span className="text-xs mt-2 text-gray-500">few new interactions</span>
          </div>
          <div className="flex flex-col items-center">
            <svg width="56" height="56">
              <circle cx="28" cy="28" r="16" fill="#1d4ed8" />
            </svg>
            <span className="text-xs mt-2 text-gray-500">many new interactions</span>
          </div>
        </div>

        <p>Edges are predicted interactions and are also color coded.</p>
        <div className="legend-2col my-6">
          <div className="flex flex-col items-center">
            <svg width="160" height="68">
              {/* known (existing) interaction */}
              <line x1="50" y1="34" x2="110" y2="34" stroke="rgba(150,150,150,0.9)" strokeWidth="3" />
              <circle cx="50" cy="34" r="14" fill="#bbb" />
              <circle cx="110" cy="34" r="18" fill="#bbb" />
            </svg>
            <span className="text-xs mt-2 text-gray-500">known interaction</span>
          </div>
          <div className="flex flex-col items-center">
            <svg width="160" height="68">
              {/* new interaction */}
              <line x1="50" y1="34" x2="110" y2="34" stroke="#3b82f6" strokeWidth="3" />
              <circle cx="50" cy="34" r="14" fill="#3b82f6" />
              <circle cx="110" cy="34" r="18" fill="#3b82f6" />
            </svg>
            <span className="text-xs mt-2 text-gray-500">new interaction</span>
          </div>
        </div>

        <p>Hovering or clicking on a node reveals its immediate (first-degree) connections. If two first-degree connections are also connected to each other, this is called an <b>interconnection</b> and is also shown.</p>
        <div className="my-6">
          {/* Interactive mini graph illustration */}
          <MiniGraph />
        </div>

        <p>We populated the tool with the <b>80% precision dataset</b>, which has: 12,298 proteins; 29,257 interactions; 7,290 of which are new interactions.</p>
      </section>

      <section>
        <h2>The Graph View</h2>
        <FigureImage
        lightSrc="/write-up/ppi-overview-light.png"
        darkSrc="/write-up/images/dark/intro-dark.png"
        alt="Overview of the PPI graph"
        caption="In the Graph View, proteins are initially distributed on a donut shape, with larger nodes located closer to the center."
      />
      </section>

      <section>
        <h3>IGLL1 and IGLL5</h3>
        <ImageCarousel
            images={[
              { src: "/write-up/images/dark/IGLL1-dark.png", alt: "IGLL1", caption: "IGLL1", href: "/?protein=IGLL1" },
              { src: "/write-up/images/dark/IGLL5-dark.png", alt: "IGLL5", caption: "IGLL5", href: "https://www.rcsb.org/structure/5G8G" },
            ]}
          />
        <p>Immediately noticeable are two dark blue proteins:  
        <HoverPreview previewUrl="/next.svg" title="IGLL1 folded 3D structure">
          IGLL1 
        </HoverPreview>
        (Immunoglobulin Lambda Like Polypeptide 1) and 
        <HoverPreview previewUrl="/next.svg" title="IGLL5 folded 3D structure">
        IGLL5 
        </HoverPreview>
        (Immunoglobulin Lambda Like Polypeptide 5). New connections are enriched in the immune system proteins category (263 new PPIs), and the majority concentrate specifically on IGLL1 and IGLL5 (171 new PPIs combined). The new predicted interactions for these two proteins are others named IGLV and IGKV (Immunoglobulin Lambda/Kappa Variable chains) – variable regions of antibodies light chains. IGLL1 also has some new interactions with IGHV proteins.</p>
      </section>
  
      <section>
        <h2>But first, what do we already know about protein-protein interactions?</h2>
        <p>
          Replace this text with your narrative. You can include headings, inline code, blockquotes, lists, and images. This page is intentionally minimal to focus on content.
        </p>
        <blockquote>
          <p>
            A concise takeaway or quote can go here.
          </p>
        </blockquote>
      </section>

      <section>
        <h2>Key observations</h2>
        <ul>
          <li>Observation one</li>
          <li>Observation two</li>
          <li>Observation three</li>
        </ul>
      </section>

      <section>
        <h2>Figures</h2>
        <p>
          Drop static images now; later we can enable a carousel and hover previews.
        </p>
        <div className="not-prose mt-4">
          <ImageCarousel
            images={[
              { src: "/graph.svg", alt: "Graph overview", caption: "Graph overview" },
              { src: "/window.svg", alt: "Window", caption: "Window placeholder" },
            ]}
          />
        </div>
        <p className="mt-6">
          Hover over this label to preview an image:
          {" "}
          <HoverPreview previewUrl="/next.svg">
            <span className="underline decoration-dotted">preview image</span>
          </HoverPreview>
        </p>
      </section>
    </article>
  );
}


